In [11]:
import numpy as np
# 과학 연산을 쉽고 빠르게 할 수 있는 패키지
# 시퀀스 데이터로 배열 생성
# arr_obj = np.array(seq_data)

In [12]:
# 2차원 배열 (행렬의 구조)
np.arange(12).reshape(4,3)
# arrange() >>> 12개 숫자 생성
# reshape(m,n) >>> m x n 행렬 생성

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
b2 = np.arange(5)
b2.shape
# >>> (5, )

(5,)

In [15]:
# arr_obj = np.linspace(start, stop[, num])
# 범위의 시작,끝을 지정하고 데이터 개수 지정하여 배열 생성
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
# random()
# 난수 발생
np.random.rand(2,3)
# >>> 실수 난수 발생

array([[0.74480494, 0.8270428 , 0.64472097],
       [0.16364391, 0.05152424, 0.19676058]])

In [17]:
np.random.rand()

0.17003326390194706

In [18]:
np.random.rand()

0.37507777471696724

In [19]:
np.random.rand()

0.7371362107274289

In [20]:
np.random.rand()

0.7945726608792448

In [21]:
# 지정한 범위 내에 난수 발생 (int)
np.random.randint(10, size=(3,4))

array([[3, 6, 2, 5],
       [6, 8, 9, 6],
       [4, 8, 6, 3]])

In [26]:
# 배열의 연산
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr2**2)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 1  4  9 16]


In [29]:
# 배열에 상수 곱하기
print(arr1 * 2)

# 배열의 비교 연산
print(arr1 > arr2)
print(arr1 > 20)

[20 40 60 80]
[ True  True  True  True]
[False False  True  True]


In [36]:
# 배열의 메서드
arr3 = np.arange(5)
print(arr3)
# >>> [0 1 2 3 4]

# sum(), mean()
# 합, 평균
print([arr3.sum(), arr3.mean()])

# 표준편차, 분산
# std(), var()
print([arr3.std(), arr3.var()])

# 최댓값, 최솟값
# max(), min()
print([arr3.max(), arr3.min()])

# 누적합, 누적곱
# cumsum(), cumprod()
arr4 = np.arange(1,5)
print(arr4)
print(arr4.cumsum())
print(arr4.cumprod())

[0 1 2 3 4]
[10, 2.0]
[1.4142135623730951, 2.0]
[4, 0]
[1 2 3 4]
[ 1  3  6 10]
[ 1  2  6 24]


In [37]:
# 행렬 연산
A = np.array([0,1,2,3]).reshape(2,2)
print(A)

B = np.array([3,2,0,1]).reshape(2,2)
print(B)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


In [38]:
# 행렬의 곱
print(A.dot(B))
print(np.dot(A,B))

[[0 1]
 [6 7]]
[[0 1]
 [6 7]]


In [39]:
# 행렬 A의 전치행렬
print(np.transpose(A))
print(A.transpose())

[[0 2]
 [1 3]]
[[0 2]
 [1 3]]


In [40]:
# 행렬 A의 역행렬 (-A)
print(np.linalg.inv(A))

[[-1.5  0.5]
 [ 1.   0. ]]


In [41]:
# 행렬 A의 행렬식
np.linalg.det(A)

-2.0

In [47]:
# 행렬의 위치 (인덱스는 0부터 시작)
a2 = np.arange(10,100,10).reshape(3,3)
print(a2)

print(a2[0,2])
# >>> 행 0, 열 2인 원소 선택 : 30

a2[2,2] = 95
print(a2)
# >>> 90 -> 95 변경.

print(a2[2])
# >>> 2행 전체 출력

print("###################")

# 행 전체 변경
a2[1] = np.array([1,2,3])
print(a2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 95]]
[70 80 95]
###################
[[10 20 30]
 [ 1  2  3]
 [70 80 95]]


In [53]:
# slicing
b1 = np.array([0,10,20,30,40,50])
print(b1[1:4])
print(b1[:3])
print(b1[2:])

[10 20 30]
[ 0 10 20]
[20 30 40 50]


In [54]:
# 배열 시작부터 끝 위치까지 원소 변경
b1 = np.array([0,10,20,30,40,50,60,70,80])
print(b1)
b1[4:] = 77
print(b1)

[ 0 10 20 30 40 50 60 70 80]
[ 0 10 20 30 77 77 77 77 77]


In [57]:
# 열 슬라이싱
b2 = np.arange(10,100,10).reshape(3,3)
print(b2)

print(b2[1:3, 1:3])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
